# These settings are generated by the chef_utils Chef cookbook.
# Do NOT edit it manually.
<%
config = node['chef_utils']['chef-server']['config']

config.each {|key0, val0|
  if val0.is_a?(Hash)
    val0.each {|key1, val1|
-%>
<%= key0 %>['<%= key1 %>'] = <%= val1.inspect %>
<%
    }
  else
-%>
<%= key0 %> <%= val0.inspect %>
<%
  end
}
-%>
<%
extra_config_str = node['chef_utils']['chef-server']['extra_config_str']
if !extra_config_str.nil? && !extra_config_str.empty?
-%>
<%= extra_config_str %>
<%
end
-%>
<%
config_str = node['chef_utils']['chef-server']['configuration']
if !config_str.nil? && !config_str.empty?
-%>
<%= config_str %>
<%
end
-%>
