driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: centos-5
  driver:
    image: dokken/centos-5
    pid_one_command: /sbin/init
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems]

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
  run_list:
    - recipe[packagecloud_test::rpm]
    - recipe[packagecloud_test::rubygems_private]

- name: ubuntu-12.04
  driver:
    image: dokken/ubuntu-12.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y man
  run_list:
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems]

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y man
  run_list:
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems]

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install -y man
  run_list:
    - recipe[packagecloud_test::deb]
    - recipe[packagecloud_test::rubygems_private]
